---
- name: Download new git repo and build docs
  block:
    - name: Set http or https protocol
      set_fact:
          http_or_https: "{{ 'https' if git_url_ssl is defined else 'http' }}" 

    - name: Enable auth if private repo
      set_fact:
          git_auth: "{{ git_login }}:{{ git_password|urlencode }}@"
      when: git_private is defined 
    
    - name: Download repo
      git:
        repo: "{{ http_or_https }}://{{ git_auth | default ('') }}{{ git_server }}/{{ item.key }}/{{ item.value }}.git"
        dest: "/var/mkdocs/{{ item.value }}"
        track_submodules: yes
      with_dict: "{{ git_project }}"
    
    - name: Build new site
      command: /var/mkdocs/.local/bin/mkdocs build
      args:
        chdir: "/var/mkdocs/{{ item.value }}"
      with_dict: "{{ git_project }}"
  become: True
  become_user: mkdocs
  loop: "{{ git_project }}"

- name: Publishing site
  block:
    - name: Copy builded site
      copy:
        src: /var/mkdocs/
        dest: /var/www/
        owner: nginx
        group: nginx
        setype: httpd_sys_content_t
        remote_src: yes

    